### ISSUE TITLE
implement offline messages / channel history (=subscription)

### ISSUE THREAD

**Issue by abma** [spring/uberserver#132]
just store to db with date/time and replay at point where user left

**Comment by gajop** [comment]
I'd like to add the following protocol commands:
1) >SUBSCRIBE(chanName)
2) >UNSUBSCRIBE(chanName)
3) >LISTSUBSCRIPTIONS()
4) <STARTLISTSUBSCRIPTION()
5) <LISTSUBSCRIPTION(chanName)
6) <ENDLISTSUBSCRIPTION()

Extend SAID, SAIDDATA, SAIDDATAPRIVATE, SAIDPRIVATE, SAIDEX, SAIDPRIVATEEX commands to contain a datetime field as well. Do this by using the named arguments.

**Comment by gajop** [comment]
TODO: discuss these commands on springrts forums

**Comment by abma** [comment]
+ would be nice if some message shows up on join that this channel is logged

**Comment by abma** [comment]
hm, thinking abouth this problem:

what to do when user is subscribed to a channel but doesn't join it?

this makes it a requirement to store the last time where user received messages from the channel for every channel. means each subscription needs sth. like a last_history_id / last_history_time.

thats imo bad as on user join/leave all these values needs to be updated.

thoughts?

**Comment by gajop** [comment]
Oh didn't see you already implemented this, nice.
Ideally it should only be sent once the user joins the channel, because it's odd for the user to receive messages from a channel he isn't it.

But I think we can also just choose the faster option, and just send it all once the user comes online. The client can then decide if it should immediately display the messages or wait until the user joins the channel (or alternatively discard them if he never does).

"imo it shouldn't be allowed by a normal user to enable history for a channel, only mods/admins should be allowed to." -> I'm not sure about that. What if I have a group of friends I want to play and chat with? Wouldn't it be beneficial if chat history would work in that case as well? (Although these feel more like "private messages" than anything else, but still).
I assume you are worried about there being too many messages saved/transmitted, which I don't is necessarily going to be a big problem. It would probably be better to just allow it for now (so small games/devs can utilize it), and we can always look for optimizations later -> which is something we'll need to do anyhow.

**Comment by abma** [comment]
> I assume you are worried about there being too many messages saved/transmitted,

no, i'm worried about storing all messages as default. thats not very intuitive and also bad for privacy. it should be transparent to users that messages are logged in a specific channel.

**Comment by abma** [comment]
some idea: timestamp should be optional and only used for offline messages. for "online" messages they aren't needed.

**Comment by gajop** [comment]
I thought this was an obvious optimization. ;)
So yes, I agree.
