### ISSUE TITLE
Create stress testing scripts

### ISSUE THREAD

**Issue by gajop** [spring/uberserver#152]
Key complaints that caused the ZK server split was the performance issues uberserver. Reportedly it couldn't handle 7000 users, although it's not clear how this was tested.

Stress tests should be divised to see what's possible. These tests should be designed to imitate user behaviour.

**Comment by abma** [comment]
> Key complaints that caused the ZK server split was the performance issues uberserver.

these complains never were public / reported, so no clue about it. also a modified uberserver version was used.

but in general uberserver doesn't scale good because a lot of incoming commands lead to broadcasts to all connected clients, see https://springrts.com/phpbb/viewtopic.php?p=567072#p567072

to fix this protocol has to be changed -> "lightweight mode"

**Comment by gajop** [comment]
Yep, I realize that and agree, which is why I want to create some reproducable stress testing -> this would hopefully give us an idea how much of an impact lightweight mode would have as well.

**Comment by abma** [comment]
creating such a script won't be easy, as it has to simulate 7000 clients which do:

- login
- ping/pong
- create battle or join existing battle
- change team/colors/...
- switch spectate/player
- write some message
- join channel
- "start" battle (if host)
- logout

**Comment by abma** [comment]
very simple version:

https://github.com/spring/uberserver/blob/master/stresstest.py
