### ISSUE TITLE
UPDATEBATTLEINFO allows tab at the end

### ISSUE THREAD

**Issue by abma** [spring/uberserver#177]
UPDATEBATTLEINFO[space]3835[space]0[space]0[space]1481928328[space]Comet[space]Catcher[space]Redux[space]v2[TAB]

add check!

**Comment by serg9** [comment]
another one
UPDATEBATTLEINFO[space]3846[space]0[space]0[space]1085734645[space]Moon[space]Quartet[space]Remake[TAB]

**Comment by serg9** [comment]
Here's the full debug log, it's all because of the map name having a tab at the end (**EOL added for readability)


Something went wrong while receiving 
E: BATTLEOPENED[S]3849[S]0[S]0[S]AndoPat[S]139.216.64.71[S]8452[S]32[S]1[S]0[S]1027531324[S]spring[T]94.1[T]Into[S]Battle_v3[T][T]adas[T]Metal[S]Factions[S]v0.7**EOL


Something went wrong while receiving 
E: UPDATEBATTLEINFO[S]3849[S]0[S]0[S]1027531324[S]Into[S]Battle_v3[T]**EOL


I'm catching and logging them now, I won't be posting this anymore.
Thanks!

**Comment by abma** [comment]
do all UPDATEBATTLEINFO & BATTLEOPENED commands have tab at the end? (didn't had the time yet to investigate this)

if so... it makes more sense to keep it but add more strict checking at server side.

**Comment by serg9** [comment]
Nope, 98% of them don't, I believe this comes from the map filename in some way.

Here's how 'normal' looks:

RECEIVED: UPDATEBATTLEINFO 3838 1 0 -182876094 Chicken_Farm_v02***EOL
RECEIVED: UPDATEBATTLEINFO 3447 1 0 -1993493856 Colorado_v1***EOL
RECEIVED: UPDATEBATTLEINFO 3687 1 0 -538795039 DesertTriad***EOL
RECEIVED: UPDATEBATTLEINFO 3688 1 0 -843447902 deserteagle***EOL

RECEIVED: UPDATEBATTLEINFO 3572 1 0 -1257913679 RECEIVED: BATTLEOPENED 3431 0 0 [durian]Autohost 78.46.100.156 8482 21 0 0 -1010508423 spring	98.0	Red Comet	Durian (Flea Bowl)	XTA test-955***EOL

RECEIVED: BATTLEOPENED 3689 0 0 [ACE]Pirine 78.193.134.82 8456 10 0 0 1290565381 spring	98.0	Dune	[5 v 5] [ACE]=Army Corps of Engineers :P ('_^)	Balanced Annihilation V8.17***EOL

etc.

So it either happens with some lobby that doesn't send data right, or it's the map thing. I'm ignoring them now.

**Comment by silentwings** [comment]
afaics the only possible cause of this is that the map actually has a tab char at the end of its name
