### ISSUE TITLE
on battle open: check if engine version is available to download

### ISSUE THREAD

**Issue by abma** [spring/uberserver#192]
- warn if its not available for a platform

maybe block opening it when engine doesn't exist at all, but allow when fetching info fails / is disabled.

**Comment by silentwings** [comment]
should apply only to botflagged hosts

**Comment by rtri** [comment]
Either block every version below 104.0 or engine development ends.

I sincerely hope I do not need to motivate this further.

**Comment by abma** [comment]
old engine version used worries me too. will take a bit until the change is applied to the server.

**Comment by silentwings** [comment]
I'll take this one on.

**Comment by specing** [comment]
This will undoubtedly discourage new game developers and it may cause existing game developers to consider setting up their own lobby server, should they find 104+ temporarily or otherwise(OpenGL?) unsuitable.

Furthermore, why not wait for the transition to 104 to happen organically and perhaps even help devs of the remaining games with the porting efforts? Right now most already run on 104.0+. I have also not found any relevant discussion about this on the spring forums.
