### ISSUE TITLE
allow a fresh login to replace an old client

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#281]
instead of https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L903, if the pw is correct then disconnect the old client instance and allow a fresh login

requested by ThinkSome - use case is people with unstable connections, who are cut off by their isp and then have to wait for their old login to timeout before they can reconnect, also seems a bit more modern to me

**Comment by MasterBel2** [comment]
How long are the clients having to wait for a fresh login?

**Comment by silentwings** [comment]
Won't fix - not really necessary and would lead to too many complications in keeping a consistent internal state.

**Comment by MasterBel2** [comment]
Easiest way to avoid complications (as I can see) is to replace [this line](https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L948) with 
`self.in_EXIT(self._root.clients.<fillintheblank>, "Logged in from other location")` and remove the `return` statement.

I'm not quite well-versed enough in Python to know exactly how this would work, so even if it doesn't, I'd love to know what the code would actually look like

**Comment by silentwings** [comment]
That would cause multiple inconsistencies in the server state due to changing of session_id & other properties.

**Comment by MasterBel2** [comment]
I don't see how it'd change sessionID. Wouldn't it effectively simulate the person logging out from one location, then logging in from the other?

**Comment by silentwings** [comment]
Oh, you want to kick them out - that results in them leaving all battles & channels, and losing all other non-db parts of their login state, which is also not good.

**Comment by MasterBel2** [comment]
The "proper" solution you have in mind would also involve a large-scale re-architect of lobbies too, I would imagine. But what's the target use case for this? 

`use case is people with unstable connections, who are cut off by their isp and then have to wait for their old login to timeout before they can reconnect`

As far as I'm aware, people usually discover they they have to reconnect because their lobbies disconnect, I.e. according to user experience, they have been logged out. Am I incorrect?

> it would just be irritating for the client and any others who depended on their presence/state.

It's more irritating to not have this solved. Please don't discount a perfectly valid 5-second fix because there exists a more "perfect" solution that is too much effort to implement instead.

For example – when Mac (similar to windows in this respect) has a kernel panic, they're not able to software-restart the computer because they can't trust the computer's current state. So they display a screen asking the user to restart the computer. They don't give up and say it's too hard and do nothing.

**Comment by silentwings** [comment]
> The "proper" solution you have in mind would also involve a large-scale re-architect of lobbies too, I would imagine

No. I have no idea where you got that idea.

> Please don't discount a perfectly valid 5-second fix because there exists a more "perfect" solution that is too much effort to implement instead.

If you come up with one, but your suggestion is frankly not good enough.

> people usually discover they they have to reconnect because their lobbies disconnect, 

If lobbies do that whilst their connection is still open (which I have never heard of) you should presumably report a bug in the lobby. 

> For example – when Mac (similar to windows in this respect) has a kernel panic, they're not able to software-restart the computer because they can't trust the computer's current state. So they display a screen asking the user to restart the computer. 

This is amusing but in 2020 you can just get an OS that works properly instead.

**Comment by MasterBel2** [comment]
Ok, never mind.
