### ISSUE TITLE
have less compat flags

### ISSUE THREAD

**Issue by silentwings** [spring/uberserver#328]
plan: 

remove the flags l, sp, cl, t, a, m, p, et (leaving only u and b).

flag summary: https://github.com/spring/uberserver/blob/master/protocol/Protocol.py#L205
m, p, et are non-issues, they already have no effect. l supercedes a.
removing l/sp/cl/t might affect legacy lobbies but they are at deaths door anyway after email verif
-> update all clients to send these flags, then delete them.

current status:

SL is ready 
Chobby is ready except for 'sp', which is not sent but seems to be supported in code (!?)
notalobby has few users and possibly unmaintained, is missing 'l' and 't', not hard to update if they want to.
SWL is unmaintained and (according to its authors) is superceded by Chobby, so won't update

SPADS is ready 
SLDB is ready
IRC-bridge is ready (doesn't send 'sp', unaffected by it)

**Comment by silentwings** [comment]
https://github.com/Spring-Chobby/Chobby/pull/459

**Comment by ForbodingAngel** [comment]
When is this going to live servers?

**Comment by silentwings** [comment]
@ForbodingAngel Your SWL package will break before this ticket ever comes into play - it will break as soon as SL is updated because at that point the server will (be configured to) require email verification on registration. 

So - it is https://springrts.com/phpbb/viewtopic.php?f=92&t=40429&p=592886#p592886 that you should watch for a date on.

**Comment by ForbodingAngel** [comment]
I dunno why github didn't deliver this email to my gmail until today. Thanks for the heads up. I see that SL has been updated. I had made an announcement in discord about it but hadn't actually done anything elsewhere. I was waiting till a day or two ahead of time. I figured I would just tell people to use sl or grab chobby or something.

I mean it's not like there is a massive playerbase to worry about here. I just feel a little bad because occasionally people will donate a dollar or two via itch (36 bucks total to date lol), so I feel a little guilt over it, but in the grand scheme of things, I believe that this will be for the best.

**Comment by silentwings** [comment]
Thanks for your understanding!

**Comment by silentwings** [comment]
n2s: 'sp' can stay for now, until its usage in chobby has been investigated

**Comment by silentwings** [comment]
fixed in https://github.com/spring/uberserver/commit/221c826f07be5541d1351a05d5e67b10663820fd
