### ISSUE TITLE
help with implimenting email verification

### ISSUE THREAD

**Issue by rosscosack** [spring/uberserver#374]
Hi
I am implementing the email notification system for the byar server.
I have created a file in the root of the uberserver directory called `server_email_account.txt`. 
In this file I have a single line `no-reply@road-flag.bnr.la`.
I have set up postfix and can send email via the `mail` command eg echo "Test mail" | mail -s "Thanks for your help" email@address.com
I can see the message successfully sent in both the recipient email inbox and the /var/log/mail.log
When I create a dummy user with a valid email address the uberserver log reports
```
2020-05-12 20:32:15 INFO  Protocol.in_REGISTER:893  [725] Successfully registered user <rossco123>.
2020-05-12 20:32:15 INFO  Protocol.in_LOGIN:1001  [725] Sent user <rossco123> the terms of service on session.
```
And yet I receive no email.

Bluestone suggested I request for some hardcoded values be un-hardcoded. 

I can see in SQLUsers.py there are some hardcoded values.
I attempted to set root.mail_user to no-reply@road-flag.bnr.la but but still no luck.

The mail log shows no attempted/failed emails relating to the verification email

**Comment by silentwings** [comment]
I attempted a registration to road-flag.bnr.la with a throwaway email
username: test56
email: xixecim615@box4mls.com
time: anout 06.50 BST

I was sent an email verififcation code, was not able to log in without using it, and I was able to log in after entering it. So the problem (which perhaps was configuration of email server) seems already fixed.

@rosscosack  

On road-flag.bnr.la, your Terms of Service repeatedly refers to springrts.com, for both moderation contact details and GDPR purposes. Our ToS at springrts.com are *not* included within uberserver, meaning (I think) that you must have manually included it in your server. Our ToS are *not* for external use - because they relate to the way that several different parts of springrts.com togther handle user data. Please remove or replace with your own; particularly do not claim that road-flag.bnr.la follows/uses the GPDR and data handling policies of springrts.com.

**Comment by silentwings** [comment]
Currently failing to reproduce / test this because when I enter road-flag.bnr.la into my SpringLobby it appears to redirect me to springrts.com

**Comment by rosscosack** [comment]
you are correct, it works now and I don't know what changed. Thanks!
So I should manually update the sql users file removing the sprintrts.com references?

here is the agreement in server_agreement.txt
```
[root@road-flag uberserver]# cat server_agreement.txt
You agree not to use any abusive, obscene, vulgar, slanderous, hateful, threatening, sexually-oriented or any other material that may violate any applicable laws. Doing so may lead to you being immediately and permanently banned; and relevant legal authorities being informed of your actions and of data which personally identifies you.
```

**Comment by rosscosack** [comment]
Please provide location of terms of service

**Comment by silentwings** [comment]
Oh, perhaps it wasn't redirecting me afterall then...

terms of service = server_agreement.txt, thanks for ffixing them

**Comment by rosscosack** [comment]
I am referring to the springrts.com references in  SQLUsers.py. I would like to confirm that this is the preferred way updating the verification email body and subject etc

**Comment by silentwings** [comment]
Oic - support for external servers isn't offered (since uberserver is tied to parts of springrts.com, and will only become tied closer in future + GDPR reasons) so yes you'll have to edit the code. I'll centralize the identity used in emails to reduce the amount of changes you'll need, for now, but realistically you may have to diverge at some point.

**Comment by silentwings** [comment]
https://github.com/spring/uberserver/commit/3cb084b6761c11dfa19e4cdbc2604c2a0b659f50
